config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home", controller: PagesController, action: :get

  devise_for :users
  resources :courses
  shallow do
    resources :users, only: [:index, :show, :update, :destroy] do
      resources :taken_courses, except: [:index, :show]
      resources :plans, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :planned_courses, only: [:new, :create, :update, :destroy]
      end
    end
  end
  match "users/:id" => "users#destroy", via: :delete, as: :destroy_user
  match "/planner", via: :get, controller: :pages, action: :planner, as: :planner
end

app/views/pages/_plan_courses.html.haml
%hr/
%section.plan-section#plan-courses
  %h2.col-xs-12
    %span.glyphicon.glyphicon-calendar
    Planned Courses
    %a.toggle-section.pull-right{ type: "button", "data-toggle" => "collapse", href: "#plan-courses-content", "aria-expanded" => "false", "aria-controls" => "plan-courses-content" }
      %span.glyphicon.glyphicon-collapse-down
      %span.sr-only collapse Planned Courses Section
  #plan-courses-content.collapse.in
    .checkbox.col-xs-12.col-md-3.col-md-offset-9
      %label#show-taken-courses-label
        %input#show-taken-courses{ type: "checkbox", value: "show-taken", checked: "checked" }
        show taken courses
    .col-xs-12
      #plan-taken-courses
        - @plan.taken_quarter_sections.each do |taken_quarter_section|
          .quarter
            %h3= taken_quarter_section[:title]
            .quarter-courses
              - index = 0
              - taken_quarter_section[:courses].each do |taken_course|
                - index += 1
                .plan-taken-course.plan-course
                  .plan-taken-course-header
                    = button_to "taken", taken_course_path(taken_course), method: :delete, class: "btn btn-default add-to-taken"
                    %h4= taken_course.full_id
                    %h5= taken_course.title
                  %p.plan-course-description{ lang: "en" }= taken_course.description
              - while index < 3
                - index += 1
                .plan-taken-course.plan-course
      - @plan.planned_quarter_sections.each do |planned_quarter_section|
        .quarter
          %h3= planned_quarter_section[:title]
          .quarter-courses
            - index = 0
            - planned_quarter_section[:courses].each_with_index do |planned_course|
              - index += 1
              .plan-planned-course.plan-course
                .plan-planned-course-header
                  = button_to "unplan", planned_course_path(planned_course), method: :delete, class: "btn btn-default unplan"
                  %h4= planned_course.full_id
                  %h5= planned_course.title
                %p.plan-course-description= planned_course.description
                - problems = @plan.get_problems_for(planned_course)
                - unless problems.size == 0
                  .problems-found
                    %span.glyphicon.glyphicon-warning-sign
                    %span.sr-only Warning!
                    - problems.each do |problem|
                      = content_tag(:p, problem)
            - while index < 3
              - index += 1
              .plan-planned-course.plan-course
                .add-planned-course-area
                  %p No Course Planned
                  %a{ href: new_plan_planned_course_path(plan_id: @plan.id) }
                    %span.glyphicon.glyphicon-plus
                    add

app/views/pages/_plan_stats.html.haml
%hr/
%section.plan-section#plan-stats
  %h2.col-xs-12
    %span.glyphicon.glyphicon-stats
    Plan Stats
    %a.toggle-section.pull-right{ type: "button", "data-toggle" => "collapse", href: "#plan-stats-content", "aria-expanded" => "false", "aria-controls" => "plan-stats-content" }
      %span.glyphicon.glyphicon-collapse-down
      %span.sr-only click to collapse Plan Stats Section
  #plan-stats-content.collapse.in
    .col-xs-12.col-md-6
      .row.progress-row#required-courses-count
        .progress-stat-label.col-xs-4= "Required Courses"
        .col-xs-8
          .progress
            = @plan.progress_bar_for(:required_course)
      .row.progress-row#distribution-courses-count
        .progress-stat-label.col-xs-4= "Distribution Courses"
        .col-xs-8
          .progress
            = @plan.progress_bar_for(:distribution_requirement)
      .row.progress-row#free-elective-courses-count
        .progress-stat-label.col-xs-4= "Free Elective Courses"
        .col-xs-8
          .progress
            = @plan.progress_bar_for(:free_elective)
      .row.progress-row#total-credits
        .progress-stat-label.col-xs-4= "Total Credits"
        .col-xs-8
          .progress
            = @plan.progress_bar_for(:total_credits)

    .col-xs-12.col-md-6
      .row.plan-stat-row#degree-duration
        .plan-stat-label.col-xs-4= "Degree Duration"
        .col-xs-8= "#{ @plan.statistics.duration_pretty }"
      .row.plan-stat-row#planned-completion
        .plan-stat-label.col-xs-4= "Planned Completion"
        .col-xs-8= "#{ @plan.statistics.planned_completion_date_pretty }"
      .row.plan-stat-row#quarters-remaining
        .plan-stat-label.col-xs-4= "Quarters Remaining"
        .col-xs-8= "#{ @plan.statistics.quarters_remaining }"
      .row.plan-stat-row#problems
        .plan-stat-label.col-xs-4= "Problems"
        .col-xs-8
          = "#{ @plan.statistics.problems_count }"

app/views/pages/_user_dashboard.html.haml
= content_for :description, "{ @user.name }'s Course Planning Dashboard"
.row
  %h1
    = "#{ @user.name }'s Degree Status"
    %h2 Degree Status:
    %ul
      %li= "Required Courses: #{@user.degree_statistics.required_course_count_pretty}"
      %li= "Distribution Requirement Courses: #{@user.degree_statistics.distribution_requirement_count_pretty}"
      %li= "Free Elective Courses: #{@user.degree_statistics.free_elective_count_pretty}"
      %li= "TOTAL: #{@user.degree_statistics.total_credits_count_pretty}"
    %h2 Taken Courses:
    %table.table
      %tbody.taken-courses
        = render @taken_courses

app/views/pages/_visitor_welcome.html.haml
= content_for :description, "Degree Planning for Drexel's MSIS Program"
%h1 Welcome

app/views/pages/home.html.haml
%section
  .col-xs-12
  - if @user.nil?
    = render partial: "visitor_welcome"
  - else
    = render partial: "user_dashboard", locals: { user: @user }

app/views/pages/planner.html.haml
- provide :title, @plan.name
- provide :description, "User #{@plan.user.email}'s '#{@plan.name}' degree plan."
%h1.col-xs-12
  = "\"#{ @plan.name }\""
  %span.small= link_to 'change', user_plans_path(@plan.user)
= render partial: "plan_stats", locals: { plan: @plan }
= render partial: "plan_courses", locals: { plan: @plan }