config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home", controller: PagesController, action: :get

  devise_for :users
  resources :courses
  shallow do
    resources :users, only: [:index, :show, :update, :destroy] do
      resources :taken_courses, except: [:index, :show]
      resources :plans, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :planned_courses, only: [:new, :create, :update, :destroy]
      end
    end
  end
  match "users/:id" => "users#destroy", via: :delete, as: :destroy_user
  match "/planner", via: :get, controller: :pages, action: :planner, as: :planner
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user, inverse_of: :plans
  has_many :planned_courses, dependent: :destroy, inverse_of: :plan
  has_many :taken_courses, through: :user
  has_many :courses, through: :planned_courses

  before_validation :ensure_active_has_value
  before_validation :ensure_active_if_user_has_no_other_plans
  validates :user, presence: true
  validates :name,
            presence: true,
            length: { minimum: 1, maximum: 35 },
            uniqueness: { scope: :user,
                          message: "a plan with that name already exists" }
  validates :active, presence: true
  after_save :deactivate_users_other_plans, if: "active = true"

  def activate!
    update(active: true)
  end

  def taken_and_planned_courses
    taken_courses.to_a + planned_courses.to_a
  end

  def statistics(reload = false)
    @statistics = PlanStatistics.new(self) if reload || @statistics.nil?
    @statistics
  end

  def taken_courses_course_ids
    taken_courses.pluck(:course_id)
  end

  def planned_courses_course_ids
    planned_courses.pluck(:course_id)
  end

  # takes either a Course instance or just a Course id
  def course_planned?(course)
    course_id = course.is_a?(Course) ? course.id : course
    planned_courses.any? do |planned_course|
      planned_course.course_id == course_id
    end
  end

  def num_planned_courses_in(quarter)
    planned_courses.where(quarter: quarter).count
  end

  private

  # Validators

  def ensure_active_has_value
    self.active = false if active.nil?
    !active.nil?
  end

  def ensure_active_if_user_has_no_other_plans
    self.active = true if user_has_no_other_plans
    active == true || user_has_other_plans
  end

  def deactivate_users_other_plans
    users_other_plans.where(active: true).update_all(active: false)
  end

  # Helper methods

  def users_other_plans
    user.plans.where("id != ?", id) unless user.nil?
  end

  def user_has_other_plans
    users_other_plans.size > 0 unless user.nil?
  end

  def user_has_no_other_plans
    users_other_plans.size == 0 unless user.nil?
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_and_authorize_plan, only: [:edit, :update, :destroy]
  after_action :verify_authorized

  # GET /users/:user_id/plans
  def index
    @user = User.find(params[:user_id])
    authorize @user, :plans_index?
  end

  # GET users/:user_id/plans/new
  def new
    plan = Plan.new(user_id: params[:user_id])
    authorize plan
    @plan = PlanDecorator.new(plan)
  end

  # GET /plans/1/edit
  def edit
    plan = Plan.find(params[:id])
    authorize plan
    @plan = PlanDecorator.new(plan)
  end

  # POST /users/:user_id/plans
  def create
    @plan = Plan.new(plan_params)
    authorize @plan
    if @plan.save
      redirect_to user_plans_path(user_id: params[:user_id]),
                  notice: "Plan was successfully created."
    else
      redirect_to new_user_plan_path(@plan.user),
                  alert: "Error creating plan. "\
                         "#{@plan.errors.full_messages.presence}"
    end
  end

  # PATCH/PUT /plans/1
  def update
    user = @plan.user
    if @plan.update(plan_params)
      redirect_to user_plans_path(user),
                  notice: "Plan was successfully updated."
    else
      redirect_to user_plans_path(user), alert: "Error updating plan."
    end
  end

  # DELETE /plans/1
  def destroy
    @plan.destroy
    redirect_to user_plans_url(@plan.user),
                notice: "Plan was successfully deleted."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_and_authorize_plan
    @plan = Plan.find(params[:id])
    authorize @plan
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def plan_params
    params.require(:plan).permit(:user_id, :name, :active)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
  def form_button_text_for(object)
    plan = object[1] if object.class == Array
    plan.new_record? ? "Create" : "Update"
  end
end

app/views/plans/_form.html.haml
= form_for @plan.form_model, html: { role: 'form' } do |f|
  %h3.form-title New Plan
  = f.hidden_field :user_id, class: 'hidden'
  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: 'form-control'
  = f.submit plan_decorator.submit_text, class: 'btn btn-primary btn-block'

app/views/plans/_plan.html.haml
%li{ id: "#{plan.name}", class: "list-group-item#{' active' if plan.active}" }
  .list-group-item-text.plan
    %h4.plan-name= plan.name
    = link_to 'delete', plan, method: :delete, data: { confirm: 'Are you sure?' }, class: "plan-delete btn btn-default"
    = link_to 'edit', edit_plan_path(plan),  class: "plan-edit btn btn-default"
    - if plan.active
      (Active Plan)
    - else
      = button_to "set active", plan_path(plan.id, plan: { active: true }), method: :put, form_class: "plan-set-active button_to", class: "btn btn-primary"

app/views/plans/edit.html.haml
- content_for :title, 'Edit Plan'
- content_for :description, 'Edit a plan.'

%section
  .col-xs-12
    %p= link_to 'Back to My Plans', user_plans_path(@plan.user)

    = form_for @plan.form_model, html: { role: 'form' } do |f|
      %h1.form-title= "Edit Plan '#{@plan.name}'"
      = f.hidden_field :user_id, class: 'hidden'
      .form-group
        = f.label :name
        = f.text_field :name, autofocus: true, class: 'form-control input-lg'
      = f.submit @plan.submit_text, class: 'btn btn-primary pull-right'

app/views/plans/index.html.haml
- content_for :title, 'Plans'
- content_for :description, "A list of the user's degree plans."
.col-xs-12.col-md-8.col-md-offset-2
  %h1 My Plans
  %ul.list-group
    = render @user.plans
.col-xs-4.col-xs-offset-4
  %a.btn.btn-primary.center-block{ href: new_user_plan_path(@user) }
    = glyphicon("plus") + " New Plan"

app/views/plans/new.html.haml
- content_for :title, 'New Plan'
- content_for :description, 'Form for creating a new plan.'
.col-xs-12
  .clearfix= link_to 'Show All Plans', user_plans_path(current_user)
  = render 'form', plan_decorator: @plan

app/views/plans/show.html.haml
- provide :title, @plan.name
- provide :description, "User #{@plan.user.email}'s '#{@plan.name}' degree plan."
%h1.col-xs-12
  = "\"#{ @plan.name }\""
  %span.small= link_to 'change', user_plans_path(@plan.user)
= render partial: "plan_stats", locals: { plan: @plan }
= render partial: "plan_courses", locals: { plan: @plan }

app/views/plans/update.js.erb
$('.alert').remove();
$('main').prepend("<%= escape_javascript(render 'layouts/messages') %>");
$('#plans-table').html("<%= escape_javascript(render @plan.user.plans(true)) %>");