config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home", controller: PagesController, action: :get

  devise_for :users
  resources :courses
  shallow do
    resources :users, only: [:index, :show, :update, :destroy] do
      resources :taken_courses, except: [:index, :show]
      resources :plans, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :planned_courses, only: [:new, :create, :update, :destroy]
      end
    end
  end
  match "users/:id" => "users#destroy", via: :delete, as: :destroy_user
  match "/planner", via: :get, controller: :pages, action: :planner, as: :planner
end

app/views/layouts/_footer.html.haml
.container
  %ul
    = raw "&copy; #{Time.current.year} #{link_to 'Rob Wise', 'https://twitter.com/RobAWise'} |"
    - if user_signed_in?
      %li= link_to "Planner", planner_path
    - else
      %li= link_to "Drexel MSIS Planner", root_path
    = render(partial: "layouts/navigation_links_left")

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#navbar-collapsible-area", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %span.navbar-brand
        - if user_signed_in?
          = link_to "Drexel MSIS Planner", planner_path
        - else
          = link_to "Drexel MSIS Planner", root_path
    .collapse.navbar-collapse#navbar-collapsible-area
      %ul.nav.navbar-nav
        = render "layouts/navigation_links_left"
      %ul.nav.navbar-nav.navbar-right
        = render "layouts/navigation_links_right"

app/views/layouts/_navigation_links_left.html.haml
%li= link_to "Courses", courses_path
- if user_signed_in?
  %li= link_to "Degree Status", root_path
- if user_signed_in? && current_user.admin?
  %li= link_to "Users", users_path

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li.gravatar
    %a.gravatar-link{ href: edit_user_registration_path }
      .gravatar-img-container
        %img.gravatar-img{ src: gravatar_url_for(current_user) }
  %li= link_to current_user.name, edit_user_registration_path, class: "user-link"
  %li
    =link_to raw("sign out <span class='glyphicon glyphicon-log-out'></span>"), destroy_user_session_path, method: :delete
- else
  %li= link_to "sign in", new_user_session_path
  %li= link_to "sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title= "#{content_for?(:title) ? yield(:title) + ' | ' : '' }Drexel MSIS Planner"
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Drexel MSIS Planner'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    %header
      = render 'layouts/navigation'
    %main.container{role: "main"}
      = render 'layouts/messages'
      .row
        = yield
    %footer
      = render 'layouts/footer'
    = debug(params) if Rails.env.development?